version: '3.8'

services:
  # Le conteneur où l'étudiant va travailler (VS Code s'attache ici)
  app:
    image: mcr.microsoft.com/devcontainers/java:1-21-bullseye
    volumes:
      - ../..:/workspaces:cached # Monte tout le projet
    command: sleep infinity
    network_mode: service:wildfly # Partage le réseau avec Wildfly pour faciliter la communication (localhost)

  # La base de données
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tpjeebdd
    network_mode: service:wildfly # Partage le réseau (localhost accessible)

  # Le serveur d'application
  wildfly:
    image: quay.io/wildfly/wildfly:30.0.0.Final-jdk21
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=localhost
    volumes:
      # Monte le script de configuration qu'on va créer
      - ./setup-wildfly.sh:/opt/jboss/wildfly/bin/setup-wildfly.sh
      # Astuce : On monte le dossier target de votre module EAR directement dans le déploiement
      # Adaptez le chemin './server-module/target/...' selon votre structure exacte
      - ../jee-with-ejb-server/jee-with-ejb-ear/target:/opt/jboss/wildfly/standalone/deployments/
    # On ouvre les ports pour qu'ils soient accessibles depuis le navigateur
    ports:
      - "8080:8080"
      - "9990:9990"
      - "5432:5432"